In [37]:
#importing libraries
import pandas as pd
import numpy as np

In [38]:
#loading the dataset from scikit learning
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [39]:
#listing the keys of dataset
print("keys of iris data set :\n{}".format(iris_dataset.keys()))

keys of iris data set :
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [41]:
# to observe DESCR column 
print(iris_dataset["DESCR"][:200]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


In [42]:
#listing out the target names
print("target names :{}".format(iris_dataset["target_names"]))

target names :['setosa' 'versicolor' 'virginica']


In [43]:
#to observe the feature names
print("feature names :\n{}".format(iris_dataset.feature_names))

feature names :
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [44]:
#to find the type of data
print("type of data :\n{}".format(type(iris_dataset["data"])))

type of data :
<class 'numpy.ndarray'>


In [45]:
#to find the shape of data
print("shape of data : {}".format(iris_dataset["data"].shape))

shape of data : (150, 4)


In [46]:
#observing first 5 coulmns of data
print("'first five columns of data :\n{}".format(iris_dataset["data"][:5]))

'first five columns of data :
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [47]:
#to find the type of target
print("type of target :{}".format(type(iris_dataset["target"])))

type of target :<class 'numpy.ndarray'>


In [48]:
#to find the shape of target
print("shape of target:{}".format(iris_dataset["target"].shape))

shape of target:(150,)


In [49]:
#observing the target column of data set
print("target:\n{}".format(iris_dataset["target"]))

target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [50]:
#setting up training data and test data
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset["data"],
                                iris_dataset["target"],random_state = 0) 

In [51]:
#observing the shape of training & test data
print("X_train shape : {}".format(X_train.shape))
print("X_test shape : {}".format(X_test.shape))
print("y_train shape : {}".format(y_train.shape))
print("y_test shape : {}".format(y_test.shape))

X_train shape : (112, 4)
X_test shape : (38, 4)
y_train shape : (112,)
y_test shape : (38,)


In [53]:
#this is the KNN machine model
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [55]:
#fitting KNN classifier to training data values
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [56]:
# making prediction for new data
X_new = np.array([[5, 2.9, 1 ,0.2]])
print("X_new.shape:{}".format(X_new.shape))

X_new.shape:(1, 4)


In [57]:
#calling predict method of Knn object to make prediction 
prediction = knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted target name : {}".format(
    iris_dataset["target_names"][prediction]))

Prediction: [0]
Predicted target name : ['setosa']


In [58]:
#evaluating the model

In [59]:
y_pred = knn.predict(X_test)
print("Test set predictions:\n {}".format(y_pred))


Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [60]:
print("Test set score : {}".format(np.mean(y_pred == y_test)))

Test set score : 0.9736842105263158
